### ISSUE TITLE
Rebuild

### ISSUE THREAD

**Issue by rvola** [mythic-beasts/login-lockdown-mb#1]
hello Mystic!

I am also a User Login Lockdown and I also created a fork on the internationalization of the plugin.
It is now one month that I warned the developer with 3 raises.

I have no news.
Unfortunately I have the impression he leaves.

Would you therefore to create a Fork and republish on WordPress together.

It would work to refactor the code, secure.

If you are interested, it might be a nice adventure

**Comment by pdw-mb** [comment]
We created this fork because we had customers using this plugin on our IPv6 network and so needed a fix.  Whilst we'd like work on republishing it on Wordpress, realistically doing further work on this is not a priority for us, and I wouldn't like to commit to an effort that we can't support properly.

You are very welcome to take what we've done and incorporate it into a new version of the plugin.

**Comment by rvola** [comment]
Hello !
Ok I understand you.

Thank you very much for your answer.
I go one last time to contact the developer.
